export const experienceList = [
  {
    companyName: "Nference",
    employmentType: "Full-Time",
    designation: "Senior Engineer",
    duration: "Apr 2022 - Present",
    companyType: "Product-based",
    companyWebsite: "",
    companyIntro: "",
    works: [],
  },
  {
    companyName: "Nference",
    employmentType: "Full-Time",
    designation: "Software Engineer",
    duration: "Jan 2021 - Mar 2022",
    companyType: "Product-based",
    companyWebsite: "",
    companyIntro: "",
    works: [],
  },
  {
    companyName: "Piktorlabs",
    employmentType: "Full-Time",
    designation: "Software Engineer",
    duration: "Jul 2019 - Jan 2021",
    companyType: "Product-based",
    companyWebsite: "",
    companyIntro: "",
    works: [],
  },
  {
    companyName: "Keitai Technologies",
    employmentType: "Internship",
    designation: "Intern",
    duration: "Dec 2018 - Jan 2019",
    companyType: "Product-based",
    companyWebsite: "",
    companyIntro: "",
    works: [],
  },
];
